# Generated by Django 4.0.2 on 2022-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('descriptions', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField()),
                ('status_task', models.CharField(choices=[('P', 'In Progress'), ('C', 'Completed'), ('N', 'Pending')], max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
